force-app/main/default/objects/Account/fields/lang__c.field-meta.xml
<CustomField>
    <fullName>lang__c</fullName>
    <label>lang</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/test_list__c.field-meta.xml
<CustomField>
    <fullName>test_list__c</fullName>
    <label>test_list</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
                <default>true</default>
                <label>January</label>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/accMonthCtrl.cls
public class accMonthCtrl {
    public Id accId {get;set;}
     public Id accIdd {get;set;}
   
    public String mon;
    
    public String getMonth() {
        if(accId!=NULL)
        return [select toLabel(test_list__c) from Account where Id =: accId].test_list__c;
        else if(accIdd!=NULL)
        return [select toLabel(lang__c) from Account where Id =: accIdd].lang__c;
        return null;
    }
    
    
}